### ISSUE TITLE
Its Not Streaming Any Web series

### ISSUE THREAD

**Issue by clearmyskin** [jarnails1559/cinestream-website#1]
Not a single series is working!!

**Comment by jarnails1559** [comment]
sorry for inconvenience, Cinestream currently available for Movies only. we are working for webseries also. stay tuned.

**Comment by clearmyskin** [comment]
Thanks, 
I want to work with you!
Do you have any server/social media handle?

**Comment by jarnails1559** [comment]
You can inbox me personally on telegram @jaxs321.
